<<<<<<< HEAD
# Generated by Django 5.2.6 on 2025-09-23 00:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_round1', models.BooleanField(default=False)),
                ('completed_round2', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round1_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('round2_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('overall_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_shortlisted', models.BooleanField(default=False)),
                ('evaluation_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hiring.candidatesession')),
            ],
        ),
        migrations.CreateModel(
            name='HiringRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_profile', models.CharField(max_length=200)),
                ('years_experience', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=20)),
                ('number_of_questions_round1', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(1)])),
                ('number_of_questions_round2', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='candidatesession',
            name='hiring_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiring.hiringrequest'),
        ),
        migrations.CreateModel(
            name='Round1Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('short', 'Short Answer')], max_length=10)),
                ('options', models.JSONField(blank=True, null=True)),
                ('correct_option_index', models.IntegerField(blank=True, null=True)),
                ('model_answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hiring_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round1_questions', to='hiring.hiringrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Round2Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_order', models.IntegerField(default=0)),
                ('model_answer', models.TextField()),
                ('audio_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hiring_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round2_questions', to='hiring.hiringrequest')),
            ],
            options={
                'ordering': ['question_order'],
            },
        ),
        migrations.CreateModel(
            name='Round1Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_answer', models.TextField()),
                ('score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round1_answers', to='hiring.candidatesession')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiring.round1question')),
            ],
            options={
                'unique_together': {('candidate_session', 'question')},
            },
        ),
        migrations.CreateModel(
            name='Round2Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_response_path', models.CharField(blank=True, max_length=500, null=True)),
                ('transcribed_text', models.TextField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('feedback', models.TextField(blank=True, null=True)),
                ('repeat_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round2_answers', to='hiring.candidatesession')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiring.round2question')),
            ],
            options={
                'unique_together': {('candidate_session', 'question')},
            },
        ),
    ]
=======
# Generated by Django 5.2.6 on 2025-09-23 00:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_round1', models.BooleanField(default=False)),
                ('completed_round2', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round1_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('round2_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('overall_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_shortlisted', models.BooleanField(default=False)),
                ('evaluation_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hiring.candidatesession')),
            ],
        ),
        migrations.CreateModel(
            name='HiringRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_profile', models.CharField(max_length=200)),
                ('years_experience', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=20)),
                ('number_of_questions_round1', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(1)])),
                ('number_of_questions_round2', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='candidatesession',
            name='hiring_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiring.hiringrequest'),
        ),
        migrations.CreateModel(
            name='Round1Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('short', 'Short Answer')], max_length=10)),
                ('options', models.JSONField(blank=True, null=True)),
                ('correct_option_index', models.IntegerField(blank=True, null=True)),
                ('model_answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hiring_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round1_questions', to='hiring.hiringrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Round2Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_order', models.IntegerField(default=0)),
                ('model_answer', models.TextField()),
                ('audio_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hiring_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round2_questions', to='hiring.hiringrequest')),
            ],
            options={
                'ordering': ['question_order'],
            },
        ),
        migrations.CreateModel(
            name='Round1Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_answer', models.TextField()),
                ('score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round1_answers', to='hiring.candidatesession')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiring.round1question')),
            ],
            options={
                'unique_together': {('candidate_session', 'question')},
            },
        ),
        migrations.CreateModel(
            name='Round2Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_response_path', models.CharField(blank=True, max_length=500, null=True)),
                ('transcribed_text', models.TextField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('feedback', models.TextField(blank=True, null=True)),
                ('repeat_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round2_answers', to='hiring.candidatesession')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiring.round2question')),
            ],
            options={
                'unique_together': {('candidate_session', 'question')},
            },
        ),
    ]
>>>>>>> 45714fc9bb77db1a37f345b9f3c925e550b03dcb
