<<<<<<< HEAD
# Generated by Django 5.2.6 on 2025-09-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatesession',
            name='current_question_index',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='round2answer',
            name='evaluation_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='round2answer',
            name='improvement_suggestions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='round2answer',
            name='keywords_matched',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
=======
# Generated by Django 5.2.6 on 2025-09-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatesession',
            name='current_question_index',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='round2answer',
            name='evaluation_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='round2answer',
            name='improvement_suggestions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='round2answer',
            name='keywords_matched',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
>>>>>>> 45714fc9bb77db1a37f345b9f3c925e550b03dcb
