# Generated by Django 5.2.6 on 2025-10-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0002_candidatesession_current_question_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatesession',
            name='termination_reason',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
