# Generated by Django 5.2.6 on 2025-10-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0003_candidatesession_termination_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatesession',
            name='is_terminated',
            field=models.BooleanField(default=False),
        ),
    ]
