# Generated by Django 5.2.6 on 2025-10-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0004_candidatesession_is_terminated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationresult',
            name='overall_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluationresult',
            name='round1_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluationresult',
            name='round2_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
