# Generated by Django 4.2.7 on 2025-10-17 13:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("hiring", "0005_alter_evaluationresult_overall_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatesession",
            name="audio_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="candidatesession",
            name="camera_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="candidatesession",
            name="is_proctoring_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="candidatesession",
            name="last_proctoring_check",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="candidatesession",
            name="proctoring_warnings_count",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="ProctoringViolation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "violation_type",
                    models.CharField(
                        choices=[
                            ("no_camera", "No Camera Detected"),
                            ("multiple_people", "Multiple People Detected"),
                            ("mobile_phone", "Mobile Phone Detected"),
                            ("person_left", "Person Left Camera View"),
                            ("looking_away", "Looking Away From Screen"),
                            ("tab_switch", "Tab Switching"),
                            ("audio_violation", "Audio Violation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("violation_timestamp", models.DateTimeField(auto_now_add=True)),
                ("violation_details", models.TextField(blank=True, null=True)),
                (
                    "screenshot_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("is_warning_issued", models.BooleanField(default=False)),
                (
                    "candidate_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proctoring_violations",
                        to="hiring.candidatesession",
                    ),
                ),
            ],
            options={
                "ordering": ["-violation_timestamp"],
            },
        ),
    ]
