# Generated by Django 4.2.7 on 2025-10-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hiring", "0006_candidatesession_audio_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="round1answer",
            name="is_correct",
            field=models.BooleanField(default=False),
        ),
    ]
