# Generated by Django 4.2.7 on 2025-11-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0007_round1answer_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatesession',
            name='system_check_completed',
            field=models.BooleanField(default=False),
        ),
    ]
