# Generated by Django 4.2.7 on 2025-11-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0008_candidatesession_system_check_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatesession',
            name='camera_warnings_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidatesession',
            name='screen_share_warnings_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidatesession',
            name='screen_sharing_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidatesession',
            name='tab_warnings_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidatesession',
            name='voice_warnings_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proctoringviolation',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='proctoringviolation',
            name='severity',
            field=models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical'), ('terminal', 'Terminal')], default='warning', max_length=20),
        ),
        migrations.AlterField(
            model_name='proctoringviolation',
            name='violation_type',
            field=models.CharField(choices=[('no_camera', 'No Camera Detected'), ('camera_off', 'Camera Turned Off'), ('camera_blocked', 'Camera Blocked'), ('multiple_people', 'Multiple People Detected'), ('person_left', 'Person Left Camera View'), ('extreme_head_turn', 'Extreme Head Turn'), ('voice_violation', 'Multiple Voices Detected'), ('tab_switch', 'Tab Switching'), ('tab_resize', 'Tab Resized'), ('screen_share', 'Screen Sharing Detected'), ('audio_violation', 'Audio Violation')], max_length=30),
        ),
    ]
