# Generated by Django 4.2.7 on 2025-11-16 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0009_candidatesession_camera_warnings_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatesession',
            name='screen_sharing_detected',
            field=models.BooleanField(default=False),
        ),
    ]
