# Generated by Django 4.2.7 on 2025-11-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0010_candidatesession_screen_sharing_detected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proctoringviolation',
            name='violation_type',
            field=models.CharField(choices=[('no_camera', 'No Camera Detected'), ('multiple_people', 'Multiple People Detected'), ('mobile_phone', 'Mobile Phone Detected'), ('person_left', 'Person Left Camera View'), ('looking_away', 'Looking Away From Screen'), ('tab_switch', 'Tab Switching'), ('audio_violation', 'Audio Violation'), ('right_click', 'Right Click on Content'), ('tab_right_click', 'Right Click on Test Tabs')], max_length=30),
        ),
    ]
