# Generated by Django 4.2.7 on 2026-02-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hiring", "0012_alter_proctoringviolation_violation_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatesession",
            name="last_violation_time",
            field=models.FloatField(default=0),
        ),
    ]
