# Generated by Django 4.2.7 on 2026-02-27 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hiring", "0013_candidatesession_last_violation_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_type",
                    models.CharField(
                        choices=[
                            ("round1_gen", "Round 1 Generation"),
                            ("round2_gen", "Round 2 Generation"),
                            ("round1_eval", "Round 1 Evaluation"),
                            ("round2_eval", "Round 2 Evaluation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tokens_used", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token_usages",
                        to="hiring.candidatesession",
                    ),
                ),
            ],
        ),
    ]
